name: assign-from-label
run-name: "assign-from-label: '${{ github.event.label.name }}'"

on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled

jobs:
  assign-from-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pietrobolcato/action-read-yaml@1.1.0
        id: metadata
        with:
          config: .github/assets/user-labels.yml

      - name: echo
        run: |
          echo ${{ github.event.label.name }}
          echo ${{ steps.metadata.outputs[github.event.label.name] }}
          echo ${{ steps.metadata.outputs['POC: Phil'] }}
          echo $(pwd)
      - name: assign
        if: ${{ steps.metadata.outputs[github.event.label.name] }} != ''
        run: |
          echo "will assign user ${{ steps.metadata.outputs[github.event.label.name] }}"
