name: Add issue/PR to user's project

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      ADD_TO_PROJECT_PAT:
        required: true

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: download yaml
        run: |
          wget https://raw.githubusercontent.com/CCBR/nf-sandbox/master/.github/user-kanbans.yml

      - uses: pietrobolcato/action-read-yaml@1.1.0
        id: metadata
        with:
          config: user-kanbans.yml

      - name: echo
        run: |
          echo ${{ inputs.username }} ${{ steps.metadata.outputs[inputs.username] }}

      - uses: actions/add-to-project@v0.5.0
        if: ${{ steps.metadata.outputs[inputs.username] != '' }}
        with:
          project-url: ${{ steps.metadata.outputs[inputs.username] }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
