name: changed-files-mtx

on:
  push:
    branches:
      - '**autobuild**'  # Only trigger if the branch name contains "autobuild"
    paths:
      - '**/Dockerfile.*'  # Only trigger if a Dockerfile.* is modified in any directory

  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**/Dockerfile.*'  # Only trigger if a Dockerfile.* is modified in any directory

env:
  SUFFIX: ${{ github.base_ref == 'main' && github.event_name == 'pull_request' && 'main' || github.base_ref == 'dev' && github.event_name == 'pull_request' && 'dev' || 'feat' }}
  dockerhub-namespace: nciccbr
  ccbr-actions-version: dockers2 # TODO change this after PR is merged

jobs:
  get-files:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.changed-files.outputs.matched_files_json }}
      files: ${{ steps.changed-files.outputs.matched_files}}
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
      - id: changed-files
        name: Check changed files
        uses: knu/changed-files@v1
        with:
          paths: |
            **/Dockerfile.*
      - name: Show changed files
        run: |
          echo "Matched files:"
          echo "${{ steps.changed-files.outputs.matched_files }}" | sed 's/^/  /'
          echo "Matched JSON"
          echo "${{ steps.changed-files.outputs.matched_json }}"

  build-docker-auto:
    needs: [get-files]
    strategy:
      matrix: ${{ fromJson(needs.get-files.outputs.json) }}
    if: ${{ fromJson(needs.get-files.outputs.json) != '' && fromJson(needs.get-files.outputs.json) != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
      - name: list changed json
        run: |
          echo ${{ matrix }}
