name: draft-release

on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: |
          Semantic version tag for next release.
          If not provided, it will be determined based on conventional commit history.
          Example: v2.5.11
        required: false
        type: string
        default: ""
      draft-branch: release-draft

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to include tags
      - uses: actions/CCBR/actions/draft-release@action-release
        with:
          github-token: ${{ github.token }}
          draft-branch: ${{ github.event.inputs.draft-branch }}
          version-tag: ${{ github.event.inputs.version-tag }}
          version-filepath: VERSION
          changelog-filepath: CHANGELOG.md
          citation-filepath: CITATION.cff
          dev-header: "development version"
