name: label-issues-repo-name

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-label:
    uses: CCBR/actions/label-issue-repo-name@vishal-actions
    with:
      github-token: ${{ github.token }}
