name: post-release

on:
  release:
    types:
      - published

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: CCBR/actions/post-release@action-release
        with:
          github-token: ${{ github.token }}
          pr-branch: release/${{ github.ref_name }}
          ccbr-actions-version: action-release
          draft-branch: release-draft
          version-filepath: VERSION
          changelog-filepath: CHANGELOG.md
          citation-filepath: CITATION.cff
          dev-header: "development version"
