name: post-release

on:
  release:
    types:
      - published

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch -c release/${{ github.ref_name }}
      - name: Bump changelog & version
        shell: python {0}
        run: |
          with open("CHANGELOG.md", "r") as infile:
            lines = infile.readlines()
          lines.prepend("## development version\n")
          with open("CHANGELOG.md", "w") as outfile:
            outfile.writelines(lines)

          with open('VERSION', 'r') as infile:
            version = infile.read().strip()
          with open('VERSION', 'w') as outfile:
            outfile.write(f"{version}-dev\n")

      - name: Open pull request
        run: |
          git add CHANGELOG.md VERSION
          git commit -m "chore: bump changelog & version after release of ${{ github.ref_name }}"

          gh pr create \
            --base main \
            --fill



