name: Add to personal projects

on:
  issues:
    types:
      - assigned
  pull_request:
    types:
      - assigned

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: pietrobolcato/action-read-yaml@v1.1.0
        id: metadata
        with:
          config: ${{ github.workspace }}/.github/user-kanbans.yml

      - name: echo
        run: |
          echo ${{ github.event.assignee.login }} ${{ steps.metadata.outputs[github.event.assignee.login] }}
          
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ steps.metadata.outputs[github.event.assignee.login] }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
