name: Add to personal projects

on:
  issues:
    types:
      - assigned
  pull_request:
    types:
      - assigned

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: CCBR/nf-sandbox/.github/workflows/auto-add-user-project.yml@master
        with:
          username: ${{ github.event.assignee.login }}
