name: Add issues/PRs to user projects

on:
  issues:
    types:
      - assigned
  pull_request:
    types:
      - assigned

jobs:
  add-to-project:
    uses: CCBR/.github/.github/workflows/auto-add-user-project.yml@reusable-workflows
    with:
      username: ${{ github.event.assignee.login }}
    secrets: inherit
